version: '3'
services:
  gitshark:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-mirror:latest
    volumes:
      - /Users/dapangyu/github-mirror/gitserver/repo:/root/repo
    ports:
      - "8001:80"
    environment:
      - DOMAIN_NAME=0.0.0.0:3000
      - WORKERS=10
      - BACKLOG=50
      - TIMEOUT=3600
  nginx:
    image: nginx:latest
    volumes:
      -  /Users/dapangyu/github-mirror/gitserver/repo:/root/repo
      - ./nginx:/etc/nginx
    ports:
      - "3000:80"
    environment:
      - DOMAIN_NAME="10.23.172.185:3000" # 必须使用外部可访问的地址域名或ip:port
  redis:
    image: redis:latest
#    ports:
#      - "6379:6379"